<?php

return [
    'options' => [
        'triggers' => [
            'weather', 'sleep_deprivation', 'hunger', 'daily_routine_disruption',
            'alcohol', 'physical_load', 'strong_smell', 'computer_work', 'stuffy_air',
            'stress', 'nerves', 'cold', 'heat', 'loud_sounds', 'bright_light',
            'sex', 'chocolate', 'dehydration', 'caffeine_withdrawal', 'menstruation',
        ],
        'pain_types' => [
            'pulsating', 'pressing', 'sharp', 'cutting', 'burning', 'aching',
            'pulling', 'shooting', 'bursting', 'humming', 'electric_shock_like',
        ],
        'localizations' => [
            'whole_head', 'headband_like', 'crown', 'neck', 'occiput', 'ear_area',
            'jaw', 'cheekbones', 'temples', 'forehead', 'above_eyes', 'left_side',
            'right_side', 'inside_and_around_eyes',
        ],
        'symptoms' => [
            'nausea', 'vomiting', 'dizziness', 'high_blood_pressure', 'runny_nose',
            'low_blood_pressure', 'tearing', 'red_eyes', 'drooping_eyelid',
            'pain_worse_with_small_noise', 'pain_worse_with_normal_light',
            'neck_stiffness', 'concentration_difficulty',
        ],
        'auras' => [
            'floaters', 'tinnitus', 'dizziness', 'speech_difficulty',
            'blurred_vision', 'narrowed_visual_field', 'zigzags',
            'finger_numbness_tingling', 'numbness_tingling', 'limb_weakness',
            'disorientation', 'light_flashes',
        ],
        'labels' => [
            'triggers' => [
                'weather' => 'Погода',
                'sleep_deprivation' => 'Недосып',
                'hunger' => 'Голод',
                'daily_routine_disruption' => 'Нарушение режима дня',
                'alcohol' => 'Алкоголь',
                'physical_load' => 'Физическая нагрузка',
                'strong_smell' => 'Сильный запах',
                'computer_work' => 'Работа за компьютером',
                'stuffy_air' => 'Духота',
                'stress' => 'Стресс',
                'nerves' => 'Нервное напряжение',
                'cold' => 'Холод',
                'heat' => 'Жара',
                'loud_sounds' => 'Громкие звуки',
                'bright_light' => 'Яркий свет',
                'sex' => 'Секс',
                'chocolate' => 'Шоколад',
                'dehydration' => 'Обезвоживание',
                'caffeine_withdrawal' => 'Отмена кофеина',
                'menstruation' => 'Менструация',
            ],
            'pain_types' => [
                'pulsating' => 'Пульсирующая',
                'pressing' => 'Давящая',
                'sharp' => 'Резкая',
                'cutting' => 'Режущая',
                'burning' => 'Жгучая',
                'aching' => 'Ноющая',
                'pulling' => 'Тянущая',
                'shooting' => 'Стреляющая',
                'bursting' => 'Распирающая',
                'humming' => 'Гудящая',
                'electric_shock_like' => 'Как удар током',
            ],
            'localizations' => [
                'whole_head' => 'Вся голова',
                'headband_like' => 'Как обруч',
                'crown' => 'Макушка',
                'neck' => 'Шея',
                'occiput' => 'Затылок',
                'ear_area' => 'Область уха',
                'jaw' => 'Челюсть',
                'cheekbones' => 'Скулы',
                'temples' => 'Виски',
                'forehead' => 'Лоб',
                'above_eyes' => 'Над глазами',
                'left_side' => 'Слева',
                'right_side' => 'Справа',
                'inside_and_around_eyes' => 'Внутри и вокруг глаз',
            ],
            'symptoms' => [
                'nausea' => 'Тошнота',
                'vomiting' => 'Рвота',
                'dizziness' => 'Головокружение',
                'high_blood_pressure' => 'Повышенное давление',
                'runny_nose' => 'Насморк',
                'low_blood_pressure' => 'Пониженное давление',
                'tearing' => 'Слезотечение',
                'red_eyes' => 'Покраснение глаз',
                'drooping_eyelid' => 'Опущение века',
                'pain_worse_with_small_noise' => 'Боль усиливается от шума',
                'pain_worse_with_normal_light' => 'Боль усиливается от света',
                'neck_stiffness' => 'Скованность шеи',
                'concentration_difficulty' => 'Трудно сосредоточиться',
            ],
            'auras' => [
                'floaters' => 'Мушки перед глазами',
                'tinnitus' => 'Шум в ушах',
                'dizziness' => 'Головокружение',
                'speech_difficulty' => 'Трудности с речью',
                'blurred_vision' => 'Затуманивание зрения',
                'narrowed_visual_field' => 'Сужение поля зрения',
                'zigzags' => 'Зигзаги перед глазами',
                'finger_numbness_tingling' => 'Онемение/покалывание пальцев',
                'numbness_tingling' => 'Онемение/покалывание',
                'limb_weakness' => 'Слабость в конечностях',
                'disorientation' => 'Дезориентация',
                'light_flashes' => 'Световые вспышки',
            ],
        ],
    ],
];
